name: 'Create PR Bot'

on:
  workflow_dispatch:

jobs:
  update-browser-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'nagash77-cypress/hello-world-javascript-action'
          ref: 'develop'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Create Pull Request
        id: create-pr
        uses: actions/github-script@v6
        env:
          BASE_BRANCH: develop
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const { createPullRequest } = require('./scripts/create-pull-request.js')

            const randomString = Math.random().toString(36).substring(2, 10);

            await createPullRequest({
              context,
              github,
              core,
              baseBranch: '${{ env.BASE_BRANCH }}',
              branchName: randomString,
              description: 'Bot created PR',
              body: 'This PR was auto-generated to update the version(s) of Chrome for driver tests',
              addToProjectBoard: true
            })
