name: 'KPI Report Generation'
on:
  # makes this workflow reusable
  workflow_call:
    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true
  
  workflow_dispatch:
    inputs:
      start-date:
        description: 'Beginning date of query (ex. 2023-06-01)'     
        required: false
      end-date:
        description: 'Ending date of query (ex. 2023-06-01)'     
        required: false
      default-other-repos:
        description: "Comma separated list of repos you want to query"
        required: false
        default: '["hello-world-javascript-action", "test-private"]'
      default-mono-repo:
        description: "The mono repo"
        required: false
        default: '["another-test"]'
      

  schedule:
    - cron: '0 17 * * 5'


jobs:
  run-kpi-reporting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'nagash77-cypress/hello-world-javascript-action'
          ref: 'develop'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Generate Non-mono Repo Open / Closed KPIs
        uses: actions/github-script@v6
        env:
          DEFAULT_REPOS: ${{ github.event.inputs.default-other-repos || '["hello-world-javascript-action", "test-private"]' }}
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/reports/open-vs-closed-issues.js')
            script.getOpenAndClosedIssueMetrics(github, context, core, ${{ env.DEFAULT_REPOS }});
      - name: Generate Cypress Mono Repo Open / Closed KPIs
        uses: actions/github-script@v6
        env:
          DEFAULT_MONO_REPO:  ${{ github.event.inputs.default-mono-repo || '["another-test"]' }}
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const core = require('@actions/core');
            const script = require('./scripts/reports/open-vs-closed-issues.js')
            script.getOpenAndClosedIssueMetrics(github, context, core, ${{ env.DEFAULT_MONO_REPO }});
      - name: Generate Triage Throughput KPIs
        id: triage-metrics
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date }}
          END_DATE: ${{ github.event.inputs.end-date }}
          PROJECT_BOARD_NUMBER: 1
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const core = require('@actions/core');
            const script = require('./scripts/reports/triage_throughput_kpis.js')
            const triageObject = script.getTriageIssueMetrics(github, context, core, "${{ env.START_DATE }}", "${{ env.END_DATE }}", "${{ env.PROJECT_BOARD_NUMBER }}");
      - name: Generate Mitigation KPIs
        id: mititagtion-metrics
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date }}
          END_DATE: ${{ github.event.inputs.end-date }}
          PROJECT_BOARD_NUMBER: 1
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const core = require('@actions/core');
            const script = require('./scripts/reports/triage_mitigation_kpis.js')
            const mitigationObject = script.getIssueMitigationMetrics(github, context, core, "${{ env.START_DATE }}", "${{ env.END_DATE }}", "${{ env.PROJECT_BOARD_NUMBER }}");
      - name: Generate KPI Report
        id: generate-report
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date }}
          END_DATE: ${{ github.event.inputs.end-date }}
          PROJECT_BOARD_NUMBER: 1
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const core = require('@actions/core');
            const script = require('./scripts/reports/generate_kpi_report.js')
            script.generateKPIReport(github, context, core, "${{ steps.triage-metrics.outputs.results }}", "${{ steps.mititagtion-metrics.outputs.results }}");
      