name: 'KPI Report Generation'
on:
  # makes this workflow reusable
  workflow_call:
    secrets:
      ADD_TO_TRIAGE_BOARD_TOKEN:
        required: true
  
  workflow_dispatch:
    inputs:
      start-date:
        description: 'Beginning date of query'     
        required: false
        default: '2023-05-31'
      end-date:
        description: 'Ending date of query'     
        required: false
        default: '2023-06-01'
      default-repos:
        description: "Comma separated list of repos you want to query"
        required: false
        default: '["hello-world-javascript-action", "test-private"]'
      

  schedule:
    - cron: '0 14 * * 5'


jobs:
  run-kpi-reporting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'nagash77-cypress/hello-world-javascript-action'
          ref: 'develop'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Generate Non-mono Repo Open / Closed KPIs
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date || '2023-01-01'}}
          END_DATE: ${{ github.event.inputs.end-date || '2023-01-08'}}
          DEFAULT_REPOS: ${{ github.event.inputs.default-repos || '["hello-world-javascript-action", "test-private"]' }}
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/reports/open-vs-closed-issues.js')
            script.getOpenAndClosedIssueMetrics(github, context, "${{ env.START_DATE }}", "${{ env.END_DATE }}", ${{ env.DEFAULT_REPOS }});
      - name: Generate Cypress Mono Repo Open / Closed KPIs
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date || '2023-01-01'}}
          END_DATE: ${{ github.event.inputs.end-date || '2023-01-08'}}
          DEFAULT_REPOS: '["another-test"]'
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/reports/open-vs-closed-issues.js')
            script.getOpenAndClosedIssueMetrics(github, context, ${{ env.START_DATE }}, ${{ env.END_DATE }}, ${{ env.DEFAULT_REPOS }});
      - name: Generate Triage Throughput KPIs
        uses: actions/github-script@v6
        env:
          START_DATE: ${{ github.event.inputs.start-date || '2023-01-01'}}
          END_DATE: ${{ github.event.inputs.end-date || '2023-01-08'}}
          PROJECT_BOARD_NUMBER: 1
        with:
          github-token: ${{ secrets.ADD_TO_TRIAGE_BOARD_TOKEN }}
          script: |
            const script = require('./scripts/reports/triage_throughput_kpis.js')
            script.getTriageIssueMetrics(github, context, "${{ env.START_DATE }}", "${{ env.END_DATE }}", "${{ env.PROJECT_BOARD_NUMBER }}");
          